<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 8" host="NOTEBOOK"><DocLocation><![CDATA[D:\NienLuan_LuanVan\LuanVan\Demo\Bin\Flight]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Flight]]></DName>
<Res><![CDATA[Res46]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Flight]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 16:10:54]]></Time>
<TimeTick>1428484254</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="664" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/8/2015 - 16:11:10]]></Time>
<TimeTick>1428484270</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Details>
<Time><![CDATA[4/8/2015 - 16:11:10]]></Time>
<TimeTick>1428484270</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="109" >
<Disp><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="109" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Try to launch SSP application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[4/8/2015 - 16:11:12]]></Time>
<TimeTick>1428484272</TimeTick>
<NodeArgs eType="User" icon="7" nRep="14" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="110" >
<Disp><![CDATA[Try to launch SSP application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 16:11:15]]></Time>
<TimeTick>1428484275</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="664" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Flight Reservations]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="26" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Flight Reservations]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="29" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="18" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Login Unsuccessful]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:11]]></Time>
<TimeTick>1428484331</TimeTick>
<NodeArgs eType="User" icon="7" nRep="30" status="Failed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Login Unsuccessful]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:17]]></Time>
<TimeTick>1428484337</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:17]]></Time>
<TimeTick>1428484337</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" status="Warning" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Agent Name:]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "Agent Name:" object's parent "Login" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:17]]></Time>
<TimeTick>1428484337</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = Login<br>Native Class = #32770<br>Location = 0<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:17]]></Time>
<TimeTick>1428484337</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="38" status="Warning" nType="Parent description" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="37" status="Failed" nType="Run Error" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Agent Name:]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:17]]></Time>
<TimeTick>1428484337</TimeTick>
<NodeArgs eType="General" icon="12" nRep="39" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="35" status="Failed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="584" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/8/2015 - 16:09:57" eTime="4/8/2015 - 16:12:17" passed="2" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Flight Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Flight Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/8/2015 - 16:12:17]]></Time>
<TimeTick>1428484337</TimeTick>
<NodeArgs eType="General" icon="13" nRep="42" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/8/2015 - 16:09:53" eTime="4/8/2015 - 16:12:17" passed="2" failed="2" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Flight Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>