<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 8" host="NOTEBOOK"><DocLocation><![CDATA[D:\NienLuan_LuanVan\LuanVan\Demo\Bin\Flight]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Flight]]></DName>
<Res><![CDATA[Res113]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Flight]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:23]]></Time>
<TimeTick>1428557663</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:24]]></Time>
<TimeTick>1428557664</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:24]]></Time>
<TimeTick>1428557664</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Passed" >
<Disp><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:24]]></Time>
<TimeTick>1428557664</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:24]]></Time>
<TimeTick>1428557664</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Try to launch Flight application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:24]]></Time>
<TimeTick>1428557664</TimeTick>
<NodeArgs eType="User" icon="8" nRep="16" status="Passed" >
<Disp><![CDATA[Try to launch Flight application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:25]]></Time>
<TimeTick>1428557665</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:28]]></Time>
<TimeTick>1428557668</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:28]]></Time>
<TimeTick>1428557668</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:29]]></Time>
<TimeTick>1428557669</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:30]]></Time>
<TimeTick>1428557670</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:33]]></Time>
<TimeTick>1428557673</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" status="Warning" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Unspecified error
]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:33]]></Time>
<TimeTick>1428557673</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = OK<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:33]]></Time>
<TimeTick>1428557673</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" status="Warning" nType="Description" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="28" status="Failed" nType="Run Error" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" status="Failed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Unspecified error<BR><BR>Function file: D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs<BR>Line (124): &quot;		Dialog(&quot;Login&quot;).WinButton(&quot;OK&quot;).Click&quot;.]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:33]]></Time>
<TimeTick>1428557673</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" status="Failed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="123" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:48]]></Time>
<TimeTick>1428557688</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/9/2015 - 12:34:48]]></Time>
<TimeTick>1428557688</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:20]]></Time>
<TimeTick>1428557720</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:25]]></Time>
<TimeTick>1428557725</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:29]]></Time>
<TimeTick>1428557729</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:29]]></Time>
<TimeTick>1428557729</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="40" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Flight Reservation.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="39" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:30]]></Time>
<TimeTick>1428557730</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["abc"]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:30]]></Time>
<TimeTick>1428557730</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["abc"]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:30]]></Time>
<TimeTick>1428557730</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" status="Warning" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Agent Name:]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:30]]></Time>
<TimeTick>1428557730</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Agent Name:]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Native Class = Edit<br>Attached Text = Agent Name:<br>]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:30]]></Time>
<TimeTick>1428557730</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="47" status="Warning" nType="Description" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Agent Name:]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="46" status="Failed" nType="Run Error" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Agent Name:]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="42" status="Failed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="125" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed<BR>Function file: D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs<BR>Line (120): &quot;		Dialog(&quot;Login&quot;).WinEdit(&quot;Agent Name:&quot;).Set DataTable.Value(&quot;UserName&quot;, &quot;Flight&quot;)&quot;.]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:30]]></Time>
<TimeTick>1428557730</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="48" status="Failed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\Flight.Common.vbs" SourceLine="119" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/9/2015 - 12:35:53]]></Time>
<TimeTick>1428557753</TimeTick>
<NodeArgs eType="General" icon="12" nRep="49" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/9/2015 - 12:34:18" eTime="4/9/2015 - 12:35:53" passed="2" failed="4" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Flight Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Flight Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="4/9/2015 - 12:34:16" eTime="4/9/2015 - 12:35:53" passed="2" failed="4" warnings="4" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Flight Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>