<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 8" host="NOTEBOOK"><DocLocation><![CDATA[D:\NienLuan_LuanVan\LuanVan\Demo\Bin\Flight]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Flight]]></DName>
<Res><![CDATA[Res80]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Flight]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:24]]></Time>
<TimeTick>1428499704</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:24]]></Time>
<TimeTick>1428499704</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:24]]></Time>
<TimeTick>1428499704</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:24]]></Time>
<TimeTick>1428499704</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:24]]></Time>
<TimeTick>1428499704</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Try to launch Flight application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:24]]></Time>
<TimeTick>1428499704</TimeTick>
<NodeArgs eType="User" icon="8" nRep="16" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Try to launch Flight application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:26]]></Time>
<TimeTick>1428499706</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:31]]></Time>
<TimeTick>1428499711</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:31]]></Time>
<TimeTick>1428499711</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:31]]></Time>
<TimeTick>1428499711</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:31]]></Time>
<TimeTick>1428499711</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Flight Reservations]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="30" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["abc"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="33" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["123"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Flight Reservations]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="43" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="42" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Flight Reservations]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:32]]></Time>
<TimeTick>1428499712</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="55" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="54" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["a"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="59" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="61" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="62" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="63" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="64" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Flight Reservations]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="66" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="71" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:33]]></Time>
<TimeTick>1428499713</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:37]]></Time>
<TimeTick>1428499717</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="77" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:42]]></Time>
<TimeTick>1428499722</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="81" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Flight Reservations.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:46]]></Time>
<TimeTick>1428499726</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Flight Reservations.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Login_App testcase is passed]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:46]]></Time>
<TimeTick>1428499726</TimeTick>
<NodeArgs eType="User" icon="8" nRep="86" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Login_App testcase is passed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:28:47]]></Time>
<TimeTick>1428499727</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="88" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:12]]></Time>
<TimeTick>1428499752</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="90" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:12]]></Time>
<TimeTick>1428499752</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:12]]></Time>
<TimeTick>1428499752</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="94" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Run "D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="93" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:13]]></Time>
<TimeTick>1428499753</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:13]]></Time>
<TimeTick>1428499753</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="96" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="95" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Try to launch Flight application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:13]]></Time>
<TimeTick>1428499753</TimeTick>
<NodeArgs eType="User" icon="8" nRep="97" status="Passed" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Try to launch Flight application at path D:\NienLuan_LuanVan\LuanVan\Demo\Built\app\flight4a.exe]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:14]]></Time>
<TimeTick>1428499754</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="99" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:27]]></Time>
<TimeTick>1428499767</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/8/2015 - 20:29:27]]></Time>
<TimeTick>1428499767</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="102" Source="D:\NienLuan_LuanVan\LuanVan\Demo\Resource\Function\FrameworkFunctions.vbs" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">